### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by pscha** [larrykollar/tines#2]
I'm unable so build tines on debian.
I've installed the ncurses and ncurses-dev and now I'm left without any further ideas

```
--- git clone https://github.com/larrykollar/tines
Cloning into 'tines'...
remote: Counting objects: 241, done.
remote: Total 241 (delta 0), reused 0 (delta 0), pack-reused 240
Receiving objects: 100% (241/241), 191.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (124/124), done.
Checking connectivity... done.

--- cd tines/

--- make
(cd src;make)
make[1]: Entering directory '/home/pscha/git/tines/src'
(cd libcli;make libcli.a)
make[2]: Entering directory '/home/pscha/git/tines/src/libcli'
cc -Wall   -c -o cli.o cli.c
cc -Wall   -c -o cli_history.o cli_history.c
cc -Wall   -c -o cli_tokenize.o cli_tokenize.c
ar rc libcli.a cli*.o
ranlib -s libcli.a
ranlib: invalid option -- 's'
make[2]: Leaving directory '/home/pscha/git/tines/src/libcli'
make[1]: Circular init_subsystems.c <- init_subsystems.c dependency dropped.
echo "/* this file is autogenerated, do not edit */">init_subsystems.c
cat *.c | grep "^\!init_" | sort | sed -e "s/^\!/void /g">>init_subsystems.c
echo "">>init_subsystems.c
echo "void init_subsystems(){">>init_subsystems.c
cat *.c | grep "^\!init_" | sort | sed -e "s/^\!/ /g">>init_subsystems.c
echo "}">>init_subsystems.c
cc -c -I. -Ilibcli -DHAVE_CONFIG_H -Wall -pedantic -g  -o init_subsystems.o init_subsystems.c
init_subsystems.c:2:1: error: unknown type name ‘Binary’
 Binary file (standard input) matches
 ^
init_subsystems.c:2:14: error: unknown type name ‘standard’
 Binary file (standard input) matches
          ^
Makefile:8: recipe for target 'init_subsystems.o' failed
make[1]: *** [init_subsystems.o] Error 1
make[1]: Leaving directory '/home/pscha/git/tines/src'
Makefile:17: recipe for target 'src/tines' failed
make: *** [src/tines] Error 2
```

greetings pscha

**Comment by larrykollar** [comment]
I haven't seen that problem on my Xubuntu box. Try removing src/init_subsystems.c and then try `make` again to see if it works. That file is automatically generated by Make. If you get the same error, reply to this & drag your init_subsystems.c file into your reply.

You might want to try pulling the latest version as well; I just updated to 1.9.21. Do `make clean;make` because I updated the prefs structure (and found another lurking bug).

**Comment by pscha** [comment]
no luck with the new version.


[after update to 1.9.21](https://github.com/larrykollar/tines/files/93976/out.1.txt)
[after removing init_subsystems](https://github.com/larrykollar/tines/files/93980/out.2.txt)

**Comment by larrykollar** [comment]
My bad -- I thought Linux had strlcpy implemented. I've inserted what I consider an ugly workaround, but it's probably easier than requiring everyone to install libbsd-dev. I've attached an updated tines.c to this message; replace yours with this and let me know what happens. It worked on Xubuntu, so it should be OK on Debian as well. (sorry about the zip, Github won't allow me to drag a C file in directly)
[tines.c.zip](https://github.com/larrykollar/tines/files/94558/tines.c.zip)

**Comment by larrykollar** [comment]
Whoops, I messed up that define. Use this zip instead.
[tines.c.zip](https://github.com/larrykollar/tines/files/94609/tines.c.zip)

**Comment by pscha** [comment]
It fixes the issue about the undefined strlcpy but I'm still unable to build it:

[without init_subsystems](https://github.com/larrykollar/tines/files/94848/out.3.txt)
[with init_subsystems](https://github.com/larrykollar/tines/files/94850/out.4.txt)

p.s.:
I don't actually mind to have libbsd-dev as a dependency but a list of dependencies would be nice in a build section at the README.md

**Comment by pscha** [comment]
I've been tinkering with tines and found, that my problem is probably a borked grep, which creates a wrong init_subsystems.c in src/Makefile. So this bug can probably be closed.

**Comment by pscha** [comment]
i've fixed it: 

The problem probably is that the .c files are mostly not ascii but ISO-8859 encoded, so grep has problems with them. 

The fix is to change the src/Makefile to 

    init_subsystems.c: *.c
        echo "/* this file is autogenerated, do not edit */">init_subsystems.c
        cat *.c | grep -a "^\!init_" | sort | sed -e "s/^\!/void /g">>init_subsystems.c
        echo "">>init_subsystems.c
        echo "void init_subsystems(){">>init_subsystems.c
        cat *.c | grep -a "^\!init_" | sort | sed -e "s/^\!/ /g">>init_subsystems.c
        echo "}">>init_subsystems.c

note the `-a` option for grep

**Comment by larrykollar** [comment]
Aha, thanks! I've been trying to ditch the ISO encoding, so maybe that problem will solve itself over time.

**Comment by larrykollar** [comment]
Everything is UTF-8, now, so I think we can safely close this one.
